
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALGORITHM COMMA COMMENT DATASOURCE DROP ENCODE EQUALS EVALUATE EXPECT EXPORT FALSE FIT FOLDS GREATER ID IMPUTE INPUT LBRACE LBRACKET LEARNER LESS LOCATION LPAREN METRICS MODEL NUMBER OPTIMIZE PARAMETERS PREDICT PREPROCESS RANDOM_STATE RBRACE RBRACKET RPAREN SAVE_TO SCALE SPLIT STRATIFY STRING TARGET TEST TRAIN TRUE TYPE USING VALIDATIONprogram : declarationsdeclarations : declarations declarationdeclarations : declarationdeclaration : DATASOURCE ID LBRACE datasource_body RBRACEdatasource_body : datasource_body datasource_fielddatasource_body : datasource_fielddatasource_field : TYPE IDdatasource_field : LOCATION STRINGdeclaration : PREPROCESS ID LBRACE preprocess_body RBRACEpreprocess_body : preprocess_body preprocess_fieldpreprocess_body : preprocess_fieldpreprocess_field : INPUT IDpreprocess_field : DROP LBRACKET list_strings RBRACKETpreprocess_field : IMPUTE ID LBRACKET list_strings RBRACKETpreprocess_field : SCALE ID LBRACKET list_strings RBRACKETpreprocess_field : ENCODE ID LBRACKET list_strings RBRACKETdeclaration : LEARNER ID LBRACE learner_body RBRACElearner_body : learner_body learner_fieldlearner_body : learner_fieldlearner_field : ALGORITHM IDlearner_field : PARAMETERS LBRACE learner_parameter_body RBRACElearner_parameter_body : learner_parameter_body learner_parameter_fieldlearner_parameter_body : learner_parameter_fieldlearner_parameter_field : ID EQUALS NUMBERvalue : TRUE\n| FALSElist_strings : list_strings COMMA STRING\n| STRING'
    
_lr_action_items = {'DATASOURCE':([0,2,3,7,29,33,40,],[4,4,-3,-2,-4,-9,-17,]),'PREPROCESS':([0,2,3,7,29,33,40,],[5,5,-3,-2,-4,-9,-17,]),'LEARNER':([0,2,3,7,29,33,40,],[6,6,-3,-2,-4,-9,-17,]),'$end':([1,2,3,7,29,33,40,],[0,-1,-3,-2,-4,-9,-17,]),'ID':([4,5,6,16,20,22,23,24,27,43,49,50,58,64,],[8,9,10,31,35,37,38,39,42,51,51,-23,-22,-24,]),'LBRACE':([8,9,10,28,],[11,12,13,43,]),'TYPE':([11,14,15,30,31,32,],[16,16,-6,-5,-7,-8,]),'LOCATION':([11,14,15,30,31,32,],[17,17,-6,-5,-7,-8,]),'INPUT':([12,18,19,34,35,52,61,62,63,],[20,20,-11,-10,-12,-13,-14,-15,-16,]),'DROP':([12,18,19,34,35,52,61,62,63,],[21,21,-11,-10,-12,-13,-14,-15,-16,]),'IMPUTE':([12,18,19,34,35,52,61,62,63,],[22,22,-11,-10,-12,-13,-14,-15,-16,]),'SCALE':([12,18,19,34,35,52,61,62,63,],[23,23,-11,-10,-12,-13,-14,-15,-16,]),'ENCODE':([12,18,19,34,35,52,61,62,63,],[24,24,-11,-10,-12,-13,-14,-15,-16,]),'ALGORITHM':([13,25,26,41,42,57,],[27,27,-19,-18,-20,-21,]),'PARAMETERS':([13,25,26,41,42,57,],[28,28,-19,-18,-20,-21,]),'RBRACE':([14,15,18,19,25,26,30,31,32,34,35,41,42,49,50,52,57,58,61,62,63,64,],[29,-6,33,-11,40,-19,-5,-7,-8,-10,-12,-18,-20,57,-23,-13,-21,-22,-14,-15,-16,-24,]),'STRING':([17,36,46,47,48,53,],[32,45,45,45,45,60,]),'LBRACKET':([21,37,38,39,],[36,46,47,48,]),'RBRACKET':([44,45,54,55,56,60,],[52,-28,61,62,63,-27,]),'COMMA':([44,45,54,55,56,60,],[53,-28,53,53,53,-27,]),'EQUALS':([51,],[59,]),'NUMBER':([59,],[64,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declarations':([0,],[2,]),'declaration':([0,2,],[3,7,]),'datasource_body':([11,],[14,]),'datasource_field':([11,14,],[15,30,]),'preprocess_body':([12,],[18,]),'preprocess_field':([12,18,],[19,34,]),'learner_body':([13,],[25,]),'learner_field':([13,25,],[26,41,]),'list_strings':([36,46,47,48,],[44,54,55,56,]),'learner_parameter_body':([43,],[49,]),'learner_parameter_field':([43,49,],[50,58,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> declarations','program',1,'p_program','LexerParser.py',114),
  ('declarations -> declarations declaration','declarations',2,'p_declarations_multiple','LexerParser.py',118),
  ('declarations -> declaration','declarations',1,'p_declarations_single','LexerParser.py',122),
  ('declaration -> DATASOURCE ID LBRACE datasource_body RBRACE','declaration',5,'p_declaration_datasource','LexerParser.py',128),
  ('datasource_body -> datasource_body datasource_field','datasource_body',2,'p_datasource_body_multiple','LexerParser.py',135),
  ('datasource_body -> datasource_field','datasource_body',1,'p_datasource_body_single','LexerParser.py',139),
  ('datasource_field -> TYPE ID','datasource_field',2,'p_datasource_field_type','LexerParser.py',143),
  ('datasource_field -> LOCATION STRING','datasource_field',2,'p_datasource_field_location','LexerParser.py',150),
  ('declaration -> PREPROCESS ID LBRACE preprocess_body RBRACE','declaration',5,'p_declaration_preprocess','LexerParser.py',159),
  ('preprocess_body -> preprocess_body preprocess_field','preprocess_body',2,'p_preprocess_body_multiple','LexerParser.py',166),
  ('preprocess_body -> preprocess_field','preprocess_body',1,'p_preprocess_body_single','LexerParser.py',170),
  ('preprocess_field -> INPUT ID','preprocess_field',2,'p_preprocess_field_input','LexerParser.py',174),
  ('preprocess_field -> DROP LBRACKET list_strings RBRACKET','preprocess_field',4,'p_preprocess_field_drop','LexerParser.py',181),
  ('preprocess_field -> IMPUTE ID LBRACKET list_strings RBRACKET','preprocess_field',5,'p_preprocess_field_impute','LexerParser.py',188),
  ('preprocess_field -> SCALE ID LBRACKET list_strings RBRACKET','preprocess_field',5,'p_preprocess_field_scale','LexerParser.py',196),
  ('preprocess_field -> ENCODE ID LBRACKET list_strings RBRACKET','preprocess_field',5,'p_preprocess_field_encode','LexerParser.py',204),
  ('declaration -> LEARNER ID LBRACE learner_body RBRACE','declaration',5,'p_declaration_learner','LexerParser.py',214),
  ('learner_body -> learner_body learner_field','learner_body',2,'p_learner_body_multiple','LexerParser.py',221),
  ('learner_body -> learner_field','learner_body',1,'p_learner_body_single','LexerParser.py',225),
  ('learner_field -> ALGORITHM ID','learner_field',2,'p_learner_field_algorithm','LexerParser.py',229),
  ('learner_field -> PARAMETERS LBRACE learner_parameter_body RBRACE','learner_field',4,'p_learner_parameter_body_fild','LexerParser.py',236),
  ('learner_parameter_body -> learner_parameter_body learner_parameter_field','learner_parameter_body',2,'p_learner_parameter_body_multiple','LexerParser.py',243),
  ('learner_parameter_body -> learner_parameter_field','learner_parameter_body',1,'p_learner_parameter_body_single','LexerParser.py',247),
  ('learner_parameter_field -> ID EQUALS NUMBER','learner_parameter_field',3,'p_learner_parameter_field_assignment','LexerParser.py',251),
  ('value -> TRUE','value',1,'p_value_bool','LexerParser.py',266),
  ('value -> FALSE','value',1,'p_value_bool','LexerParser.py',267),
  ('list_strings -> list_strings COMMA STRING','list_strings',3,'p_string_list','LexerParser.py',275),
  ('list_strings -> STRING','list_strings',1,'p_string_list','LexerParser.py',276),
]
